version: 1
disable_existing_loggers: True

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG  # Set the desired log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: project.log  # Customize log file name

loggers:
  feat_eng:
    level: DEBUG
    handlers: [console, file]
    propagate: False

  preprocessing:
    level: DEBUG
    handlers: [console, file]
    propagate: False

  train:
    level: DEBUG
    handlers: [console, file]
    propagate: False

  evaluate_exog:
    level: DEBUG
    handlers: [console, file]
    propagate: False

  predict:
    level: DEBUG
    handlers: [console, file]
    propagate: False

  run_cross_validation:
    level: DEBUG
    handlers: [console, file]
    propagate: False

  run_cross_validation_new_features:
    level: DEBUG
    handlers: [console, file]
    propagate: False

  run_train_and_predict:
    level: DEBUG
    handlers: [console, file]
    propagate: False

  # ...add more loggers for other scripts

root:
    level: INFO
    handlers: [console, file]
