# project_config.yaml

data_config:
  period: 5y
  interval: 1d
  ticker_list: 
    - BOVA11.SA
    - BCFF11.SA
    - TAEE4.SA
    - EGIE3.SA
    - BBSE3.SA
    - CSMG3.SA
    - PETR4.SA
    - BRSR6.SA

  paths:
    root_data_path: ./data
    raw_data_path: data/raw
    processed_data_path: data/processed
    output_data_path: data/output
    models_path: ./models

  table_names:
    raw_table_name: dados_historicos_ate_maio.csv
    processed_table_name: processed_df.csv
    output_table_name: forecast_output_df.csv
    model_performance_table_name: model_performance_daily.csv
    cross_validation_table_name: validation_results.csv

features_list:
  - DAY_OF_MONTH
  - DAY_OF_WEEK
  - WEEK_OF_MONTH
  - MONTH
  - QUARTER
  - YEAR
  - QUANTIDADE_LAG_1
  - QUANTIDADE_LAG_2
  - QUANTIDADE_MA_3


model_config:
  tune_params: True
  save_model: True
  validation_metric: MAPE
  optimization_metric: MSE
  scoring_metric: neg_mean_absolute_error
  model_name: COPA_VENDAS
  target_col: QUANTIDADE
  predicted_col: FORECAST
  category_col: UNIDADE
  forecast_horizon: 7
  wfv_steps: 0
  available_models:
    - XGB